### ISSUE TITLE
determining correct price

### ISSUE THREAD

**Issue by rebroad** [pooleja/TranscodeE16#1]
The current default price seems a little on the low side, and also too simplistic. Surely the resolution of the video also affects the price, not just the duration. Also, it would be ideal if it could ask the installer for the price per KWHr of their electricity and the Wattage of their node in order to more correctly determine what the price should be.

**Comment by pooleja** [comment]
That is intriguing.  What would you do if I told you my electricity price was $0.10 KWHr and I was running a 1000w server?

**Comment by pooleja** [comment]
Closing as old.
